/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  Supplier as PrismaSupplier,
  Device as PrismaDevice,
} from "@prisma/client";
import { SupplierCreateInput } from "./SupplierCreateInput";
import { Supplier } from "./Supplier";
import { DeleteSupplierArgs } from "./DeleteSupplierArgs";
import { SupplierFindManyArgs } from "./SupplierFindManyArgs";
import { SupplierUpdateInput } from "./SupplierUpdateInput";

export class SupplierServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.SupplierCountArgs, "select">): Promise<number> {
    return this.prisma.supplier.count(args);
  }

  async suppliers(
    args: Prisma.SupplierFindManyArgs
  ): Promise<PrismaSupplier[]> {
    return this.prisma.supplier.findMany(args);
  }
  async supplier(
    args: Prisma.SupplierFindUniqueArgs
  ): Promise<PrismaSupplier | null> {
    return this.prisma.supplier.findUnique(args);
  }
  async createSupplier(
    args: Prisma.SupplierCreateArgs
  ): Promise<PrismaSupplier> {
    return this.prisma.supplier.create(args);
  }
  async updateSupplier(
    args: Prisma.SupplierUpdateArgs
  ): Promise<PrismaSupplier> {
    return this.prisma.supplier.update(args);
  }
  async deleteSupplier(
    args: Prisma.SupplierDeleteArgs
  ): Promise<PrismaSupplier> {
    return this.prisma.supplier.delete(args);
  }

  async findDevices(
    parentId: string,
    args: Prisma.DeviceFindManyArgs
  ): Promise<PrismaDevice[]> {
    return this.prisma.supplier
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .devices(args);
  }
  async CreateSupplierRecord(args: SupplierCreateInput): Promise<Supplier> {
    throw new Error("Not implemented");
  }
  async DeleteSupplierRecord(args: DeleteSupplierArgs): Promise<Supplier> {
    throw new Error("Not implemented");
  }
  async GetSuppliers(args: SupplierFindManyArgs): Promise<Supplier[]> {
    throw new Error("Not implemented");
  }
  async UpdateSupplierInfo(args: SupplierUpdateInput): Promise<Supplier> {
    throw new Error("Not implemented");
  }
}
