/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { DeviceService } from "../device.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { DeviceCreateInput } from "./DeviceCreateInput";
import { Device } from "./Device";
import { DeviceFindManyArgs } from "./DeviceFindManyArgs";
import { DeviceWhereUniqueInput } from "./DeviceWhereUniqueInput";
import { DeviceUpdateInput } from "./DeviceUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class DeviceControllerBase {
  constructor(
    protected readonly service: DeviceService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Device })
  @nestAccessControl.UseRoles({
    resource: "Device",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createDevice(@common.Body() data: DeviceCreateInput): Promise<Device> {
    return await this.service.createDevice({
      data: {
        ...data,

        supplier: data.supplier
          ? {
              connect: data.supplier,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        expiryDate: true,
        id: true,
        manufactureDate: true,
        model: true,
        name: true,
        serialNumber: true,
        status: true,

        supplier: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Device] })
  @ApiNestedQuery(DeviceFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Device",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async devices(@common.Req() request: Request): Promise<Device[]> {
    const args = plainToClass(DeviceFindManyArgs, request.query);
    return this.service.devices({
      ...args,
      select: {
        createdAt: true,
        expiryDate: true,
        id: true,
        manufactureDate: true,
        model: true,
        name: true,
        serialNumber: true,
        status: true,

        supplier: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Device })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Device",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async device(
    @common.Param() params: DeviceWhereUniqueInput
  ): Promise<Device | null> {
    const result = await this.service.device({
      where: params,
      select: {
        createdAt: true,
        expiryDate: true,
        id: true,
        manufactureDate: true,
        model: true,
        name: true,
        serialNumber: true,
        status: true,

        supplier: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Device })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Device",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateDevice(
    @common.Param() params: DeviceWhereUniqueInput,
    @common.Body() data: DeviceUpdateInput
  ): Promise<Device | null> {
    try {
      return await this.service.updateDevice({
        where: params,
        data: {
          ...data,

          supplier: data.supplier
            ? {
                connect: data.supplier,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          expiryDate: true,
          id: true,
          manufactureDate: true,
          model: true,
          name: true,
          serialNumber: true,
          status: true,

          supplier: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Device })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Device",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteDevice(
    @common.Param() params: DeviceWhereUniqueInput
  ): Promise<Device | null> {
    try {
      return await this.service.deleteDevice({
        where: params,
        select: {
          createdAt: true,
          expiryDate: true,
          id: true,
          manufactureDate: true,
          model: true,
          name: true,
          serialNumber: true,
          status: true,

          supplier: {
            select: {
              id: true,
            },
          },

          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/get-devices")
  @swagger.ApiOkResponse({
    type: String,
  })
  @swagger.ApiNotFoundResponse({
    type: errors.NotFoundException,
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async GetDevices(
    @common.Body()
    body: string
  ): Promise<string> {
    return this.service.GetDevices(body);
  }
}
